// This file is generated by the openedx/frontend-platform's "intl-import.js" script.
//
// Refer to the i18n documents in https://docs.openedx.org/en/latest/developers/references/i18n.html to update
// the file and use the Micro-frontend i18n pattern in new repositories.
//

// Skipped import due to missing '#/index.js' likely due to empty translations..
// Skipped import due to missing 'This/index.js' likely due to empty translations..
// Skipped import due to missing 'target/index.js' likely due to empty translations..
// Skipped import due to missing 'is/index.js' likely due to empty translations..
// Skipped import due to missing 'used/index.js' likely due to empty translations..
// Skipped import due to missing 'by/index.js' likely due to empty translations..
// Skipped import due to missing 'CI./index.js' likely due to empty translations..

export default [

];
